test: Adding premium disk support to ss and deployments on e2e tests.
abhisheksinghbaghel/azuredisk-csi-driver pull request #89
Opened 2021-06-15 22:50 UTC by landreasyan

…Also adding an extender e2e test with volume attachments replicas.

**What type of PR is this?**
Adds support of premium disks with maxshares>1 to statefulsets and deployments in e2e test suite. Also adds a scheduler extender test with volumes with maxshare=2 to check for scheduling in the presence of replica volume attachments.  

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

2021-06-15 23:11 UTC, landreasyan commented
Replica azvolumeattachments are currently not being created for the maxshare>0 case. I am investigating the issue and plan to merge this PR once I have a root cause.

2021-06-16 20:49 UTC, edreed approved these changes

2021-06-16 20:51 UTC, edreed commented
It looks like the e2e test failures are fixed by #88. It would be good to rebase on master to get a clean test run.

2021-07-29 00:08 UTC, landreasyan commented on pkg/azdiskschedulerextender/azdiskschedulerextender_metrics.go
> +	// PrioritizeNodesRequestCount = metrics.NewCounter(
Will be removing `PrioritizeNodesRequestCount` and `CacheSize` as those are not used for the scheduler extender.

2021-07-29 20:17 UTC, edreed commented on charts/index.yaml
> +    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/chart/v2.0.0-alpha.1/azuredisk-csi-driver-v2.0.0-alpha.1.tgz
It looks like the wrong URL was used when the repo index was updated.

2021-07-29 20:21 UTC, edreed requested changes
Need to fix the URL in the Helm chart repo index, but otherwise LGTM.

2021-07-30 18:17 UTC, edreed approved these changes

2021-07-30 23:18 UTC, landreasyan commented
The failure in integration test is fixed by @mukhoakash's PR - https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/blob/4580be6335a126a69bc1fdcdb53beb183296356e/pkg/provisioner/crdprovisioner.go#L562

2021-07-30 23:18 UTC, merged